### ISSUE TITLE
international dateline crash

### ISSUE THREAD

**Issue by DanGDroid** [novalabio/react-native-maps-super-cluster#20]
crash report.
RN 0.51,
react-native-maps ^0.18.3,
react-native-maps-super-cluster ^1.3.1,

description:
when user swipes the map over the international dateline:
Android:  app crashes.
iOS:         no crash.    (but did not try to put markers on that line)

i'v opened the same issue in mapbox supercluster - but it might be as your use of the lib because it crashes in your demo app as well.

see in git : [https://github.com/mapbox/supercluster/issues/73#issuecomment-364886434](url)

the crash log is of:
02-13 10:16:04.853  2656  3420 E ReactNativeJS: undefined is not an object (evaluating 'tree.range')
in `getCluster` method in `index.js` of supercluster:
```javascript  getClusters: function (bbox, zoom) {
        if (bbox[0] > bbox[2]) {
            var easternHem = this.getClusters([bbox[0], bbox[1], 180, bbox[3]], zoom);
            var westernHem = this.getClusters([-180, bbox[1], bbox[2], bbox[3]], zoom);
            return easternHem.concat(westernHem);
        }

        var tree = this.trees[this._limitZoom(zoom)];
        var ids = tree.range(lngX(bbox[0]), latY(bbox[3]), lngX(bbox[2]), latY(bbox[1]));
        var clusters = [];
        for (var i = 0; i < ids.length; i++) {
            var c = tree.points[ids[i]];
            clusters.push(c.numPoints ? getClusterJSON(c) : this.points[c.id]);
        }
        return clusters;
    },
```

thanx for the good work!

**Comment by DanGDroid** [comment]
i think this is a bug, you do'nt handle the dateline cross when you create bbox for region in `regionToBoundingBox` - when you cross the dateline the `mapView` `region.longitudeDalta` becomes negative because Google maps longitude over 180 becomes -180 and vise versa.

see log for `regionToBoundingBox` :
```javascript
CLUSTER: region: {"longitudeDelta":64.23205990344286,"latitudeDelta":49.10602875012262,"longitude":133.61212698742747,"latitude":54.49704567851359} 
bbox: [69.38006708398461,5.391016928390968,197.84418689087033,103.6030744286362]
CLUSTER: region: {"longitudeDelta":-295.76794009655714,"latitudeDelta":48.02582777381801,"longitude":167.71870555356145,"latitude":55.33785553856991} 
bbox: [463.4866456501186,7.312027764751903,-128.0492345429957,103.36368331238792]
```

a patch not to crash the map is to adjust the negative lngDelta.
though i doent know if the cluster works well on markers set on the dateline region,
elsewhere they work fine .

```javascript
export const regionToBoundingBox = (region) => {
  let lngD;
  if(region.longitudeDelta < 0)
      lngD = region.longitudeDelta + 360
  else
      lngD = region.longitudeDelta;     
  return([
  region.longitude - lngD, // westLng - min lng
  region.latitude - region.latitudeDelta, // southLat - min lat
  region.longitude + lngD, // eastLng - max lng
  region.latitude + region.latitudeDelta // northLat - max lat
])}
```
and log:
```javascript
ClusteredMapView.js:99 CLUSTER: region: {"longitudeDelta":72.32140850275755,"latitudeDelta":51.41965133790233,"longitude":-143.59275011345744,"latitude":55.52553858490292} 
bbox: [-215.914158616215,4.105887247000588,-71.27134161069989,106.94518992280524]
ClusteredMapView.js:99 CLUSTER: region: {"longitudeDelta":-287.67859149724245,"latitudeDelta":51.563363074506796,"longitude":-147.60658839717507,"latitude":55.42303466407218} 
bbox: [-219.92799689993262,3.8596715895653873,-75.28517989441752,106.98639773857897]
ClusteredMapView.js:99 CLUSTER: region: {"longitudeDelta":72.32140850275755,"latitudeDelta":54.64888430690819,"longitude":129.13044238463044,"latitude":53.20603225709386} 
bbox: [56.80903388187289,-1.4428520498143271,201.451850887388,107.85491656400205]
```

**Comment by 39otrebla** [comment]
Thanks, we'll look into this asap.

**Comment by GarimaMathur07** [comment]
@39otrebla Is there any update on this issue fix

**Comment by 39otrebla** [comment]
I merged #21, it should be fixed. Closing for now.

**Comment by thanh90** [comment]
change the zoom value to integer solved my problem

**Comment by MirkoVerdecchia** [comment]
I'm still have the problem, map is still crashin when crossing the international dateline? Some help please?

**Comment by choaibe-ifaoui** [comment]
TypeError: Cannot read property 'range' of undefined
Any update on this error?
